spring:
  #增加application.druid.yml 的配置文件
  #  profiles:
  #    active: rabbitmq

  rabbitmq:
    ####连接地址
    host: 127.0.0.1
    ####端口号
    port: 5672
    ####账号
    username: rabbit
    ####密码
    password: Mm518147#
    ### 地址
    virtual-host: /

server:
  port: 8082