
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall
    username: root
    password: Mm518147&
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: jcache
    ehcache:
      config: classpath:ehcache.xml
mybatis:
  mapper-locations:
    - classpath*:/mapper/**mapper.xml
