spring:
  profiles:
    active:
      - redis
      - cache
      - mybatis
  application:
    name: redis-cache
  boot:
    admin:
      client:
        url: http://localhost:8081
# 将所有的监控endpoint暴露出来
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: application.log






