spring:
  data:
    redis:
      # 数据库（默认为0号库）
      # database: 2
      # 密码（默认空），操作redis需要使用的密码
      password: mm518147
      #      host: 192.168.0.100
      #      port: 7001
      # 端口号
      #    port: 6379
      #连接超时时间（毫秒）
      timeout: 10000ms
      sentinel:
        master: mymaster
        nodes:
          - 192.168.0.100:6001
          - 192.168.0.100:6002
          - 192.168.0.100:6003
        # 操作sentinel时需要提供的密码
        password: mm518147
      # 使用lettuce配置
      client-type: lettuce
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 200
          # 连接池中的最大空闲连接
          max-idle: 20
          # 连接池中的最小空闲连接
          min-idle: 5
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  cache:
    type: redis   # 指定使用的缓存类型
    # redis:    当自定义ChacheManager时，就这里的配置不需要配置，配置了也不起作用
    #   use-key-prefix: true
    #  key-prefix: "demo:"
    #  time-to-live: 60000  #缓存超时时间 单位：ms
    #  cache-null-values: false #是否缓存空值
    cache-names: user

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall
    username: root
    password: Mm518147&
    driver-class-name: com.mysql.cj.jdbc.Driver


cache:
  ttl: '{"user":60,"dept":30 * 3}'
  env: dev
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






